import { useState, useEffect } from 'react';
import { client } from '@/lib/contentful';
import Head from 'next/head';
import RecipeTile from '@/components/RecipeTile';
import styles from '@/styles/Home.module.css';


export default function Home({recipes}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=""> 
        <div className={styles.actions}>
          <button className="btn btn--cta">Refresh</button>
          <button className="btn btn--cta">Show ingredients</button>
        </div>
        <div className={styles.recipes}>
          {recipes.map((recipe, index) => <RecipeTile key={index} data={recipe.fields} />)}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const response = await client.getEntries({content_type: 'recipe'})

  return {
    props: {
      recipes: response.items,
      revalidate: 7000
    }
  }
}
